inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AsciiComments:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 4

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
