AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
  TargetRubyVersion: 2.5.0

inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 137

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130

Rails/FilePath:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 4

