version: '3'
services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    restart: always
    
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db